version: '3.8'
services:
    web:
        build: .
        command: python /myproject/myproject/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/myproject
        ports:
            - 8000:8000